baseURL: 'https://johncodes.com/'
languageCode: 'en-us'
title: 'John McBride'
paginate: 5
theme: 'PaperMod'

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Talks
          url: talks/
          weight: 2
        - name: PGP Key
          url: pgp-key.txt
          weight: 20
        - name: About
          url: about
          weight: 5
        - name: Interview Prep
          url: interview-prep/
          weight: 1
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10

# home-info mode
params:
  ShowFullTextinRSS: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: John-McBride
  description: ""
  keywords: [Blog, Software Engineer, Software Developer blog, Software developer]
  #author: John McBride
  DateFormat: "January 2, 2006"
  defaultTheme: "dark"
  disableThemeToggle: false
  ShowReadingTime: false
  editPost:
    URL: "https://github.com/jpmcb/blog/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  ShowCodeCopyButtons: true

  # Home profile mode
  homeInfoParams:
    #Title : ' 📝'
    Content: |
      This is my personal landing page and blog about technology, software engineering, and programming.
      I am a software engineer by trade, so most things here revolve around that.
      But, at times, I may post short stories, photos, videos, things about philosophy, and really, whatever I want.
  socialIcons:
    - name: "rss"
      url: "https://johncodes.com/index.xml"
    - name: github
      url: "https://github.com/jpmcb"
    - name: linkedin
      url: "https://linkedin.com/in/jpmcb"
    - name: youtube
      url: "https://youtube.com/c/JohnCodes"
    - name: mastodon
      url: "https://fosstodon.org/@johnmcbride"
    - name: twitter
      url: "https://twitter.com/johncodezzz"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
